- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present

- name: Upload index.html to remote machine
  copy:
    src: roles/nginx/files/index.html
    dest: /usr/share/nginx/html/
    mode: 0644
    owner: root 
  notify:
    - restart_nginx
 
- name: Allow firewall port 80 and 443
  firewalld:
    port: "{{ item }}"
    state: enabled
    immediate: true
    permanent: true
  loop:
    - 80/tcp
    - 443/tcp
