---
- hosts: domain
  tasks:
  - name: Ansible Jinja2 for loop statement
    debug:
      msg: >
           --== Ansible Jinja2 for with break statement ==--
           {% for nilai in range(10, 0, -1) -%}
           {% if nilai == 5 -%}
           {% break %}
           {% endif -%}
           {{ nilai }}
           {% endfor %}

