---
- hosts: domain
  tasks:
  - name: Ansible Jinja2 for loop statement
    debug:
      msg: >
           --== Ansible Jinja2 for with continue statement ==--
           {% for nilai in range(10, 0, -1) -%}
           {% if nilai is odd -%}
           {% continue %}
           {% endif -%}
           {{ nilai }}
           {% endfor %}

