---

- name: Download MySQL Community repositori
  get_url:
    url: http://repo.mysql.com/mysql-community-release-el7-7.noarch.rpm
    dest: /tmp

#- name: Install MySQL Community repositori
#  command: /usr/bin/rpm -ivh /tmp/mysql-community-release-el7-7.noarch.rpm

- name: Install MySQL Server
  yum: 
    name: mysql-server
    state: present

- name: generate password root mysql
  command: openssl rand -hex 7 creates=/root/.my.cnf
  register: mysql_new_root_password

- name: tampilkan hasil generate password mysql
  debug:
     msg: password baru root mysql adalah "{{ mysql_new_root_password.stdout }}"
  when: mysql_new_root_password.changed

- name: Install MySQL-Python (untuk remove anonymous user)
  yum: 
    name: MySQL-python
    state: present

- name: start and enable mysql-server
  systemd:
    name: mysqld
    state: started
    enabled: true

#- name: Ensure mysql root password is updated for all root accounts
#  mysql_user:
#    name: root
#    host: "{{ item }}"
#    login_unix_socket: /var/run/mysqld/mysqld.sock
#    password: "{{ mysql.root_db_password }}"
#    priv: '*.*:ALL,GRANT'
#    check_implicit_admin: true
#  loop: "{{ mysql.hosts }}"
#  become: yes
#  notify: Restart MySQL

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src: /etc/ansible/roles/apache/templates/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  become: yes

- name: rubah root password
  mysql_user:
     name: root
     host: "{{ item }}"
     password: "{{ root_db_password }}"
  loop:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Remove test database jika ada
  mysql_db:
     name: test
     state: absent

- name: Remove semua anonymous user mysql
  mysql_user:
     name: ''
     host_all: yes
     state: absent

